<?php

/**
 * @file
 * Code for the know4pol-ecl feature.
 */

/**
 * Implements hook_wysiwyg_plugin().
 */
function know4pol_ecl_wysiwyg_plugin($editor, $version) {
  $plugins = array();
  switch ($editor) {
    case 'ckeditor':
      if ($version > 4) {
        $plugins['ctabutton'] = array(
          'path' => drupal_get_path('module', 'know4pol_ecl') . '/plugins/ctabutton',
          'filename' => 'plugin.js',
          'load' => TRUE,
          'buttons' => array(
            'ctabutton' => t('Call to action'),
          ),
        );
      }
      break;
  }
  return $plugins;
}

/**
 * Implements hook_wysiwyg_editor_settings_alter().
 */
function know4pol_ecl_wysiwyg_editor_settings_alter(&$settings, $context) {
  global $base_url;

  // Only ckeditor configuration;
  if ($context['profile']->editor != 'ckeditor') return;
  
  // Apply source formating when viewing html source.
  $settings['apply_source_formatting'] = 1;
  $settings['cleanup_on_startup'] = TRUE;

  // Available default values: "p;h2;h3;h4;h5;h6".
  $settings['format_tags'] = "Paragraph;h2;h3;h4;h5;h6";

  // Change the default format p.
  $settings['format_Paragraph']['name'] = 'Paragraph';
  $settings['format_Paragraph']['element'] = 'p';

  // Settings ckeditor to use theme css.
  $settings['contentsCss'] = [
    '0' => $base_url . '/' . drupal_get_path('theme', 'ec_europa') . '/assets/styles/wysiwyg/editor.css',
    '1' => $base_url . '/' . drupal_get_path('theme', 'ec_europa') . '/assets/styles/europa.css',
    '2' => $base_url . '/' . drupal_get_path('theme', 'know4pol_ec_europa') . '/assets/styles/know4pol_ec_europa.css',
    '3' => $base_url . '/' . drupal_get_path('module', 'know4pol_core') . '/css/know4pol_core.css',
  ];

  $settings['bodyClass'] = 'padding-wysiwyg-body';

  // Make sure the toolbar is there.
  if (!empty($settings['toolbar'])) {
    $new_toolbar = [];
    // These are our desired groupings.
    
    switch ($context['profile']->format) {
      case 'basic_html':
        $new_toolbar[] = ['Bold', 'Italic', 'Underline', 'SpecialChar'];
        $new_toolbar[] = ['Link', 'NextEuropaToken', 'Unlink'];
        $new_toolbar[] = ['BulletedList', 'NumberedList'];
        $new_toolbar[] = ['PasteFromWord', 'PasteText', 'RemoveFormat'];
        break;
        
      case 'filtered_html':
        $new_toolbar[] = ['Format'];
        $new_toolbar[] = ['Bold', 'Italic', 'Underline', 'Subscript', 'Superscript', 'SpecialChar'];
        
        $new_toolbar[] = ['Link', 'NextEuropaToken', 'Unlink', 'Anchor'];          
        $new_toolbar[] = ['BulletedList', 'NumberedList', 'Outdent', 'Indent'];
        $new_toolbar[] = ['PasteFromWord', 'PasteText', 'RemoveFormat'];  
        break;
        
      case 'full_html':
        $new_toolbar[] = ['Format'];
        $new_toolbar[] = [
          'Bold',
          'Italic',
          'Underline',
          'Subscript',
          'Superscript',
          'SpecialChar',
          'HorizontalRule',
        ];
        $new_toolbar[] = ['Link', 'NextEuropaToken', 'Unlink', 'Anchor'];          
        $new_toolbar[] = ['BulletedList', 'NumberedList', 'Outdent', 'Indent'];
        $new_toolbar[] = ['PasteFromWord', 'PasteText', 'RemoveFormat'];  
        $new_toolbar[] = [
          'Table',
          'Blockquote',
          'media',
          'Iframe',
          'collapse',
          'ctabutton',
        ];
        break;
    }

    $new_toolbar[] = ['Undo', 'Maximize'];
    $new_toolbar[] = [
      'lite_AcceptAll',
      'lite_RejectAll',
      'lite_AcceptOne',
      'lite_RejectOne',
      'lite_ToggleShow',
      'lite_ToggleTracking',
    ];
    
    if($context['profile']->format != 'basic_html') {
      $new_toolbar[] = ['ShowBlocks', 'Source'];
    }
    
    $settings['toolbar'] = $new_toolbar;
  }

  elseif (!empty($settings['toolbar']) && $context['profile']->format == 'filtered') {
    $new_toolbar[] = [
      'dt_headings',
      'Link',
      'NextEuropaToken',
      'BulletedList',
    ];

    $new_toolbar[] = [
      'Undo',
      'Source',
    ];

    $settings['toolbar'] = $new_toolbar;
  }
}
