<?php

/**
 * @file
 * Code for the know4pol-ecl feature.
 */

/**
 * Implements hook_wysiwyg_plugin().
 */
function know4pol_ecl_wysiwyg_plugin($editor, $version) {
  $plugins = array();
  switch ($editor) {
    case 'ckeditor':
      if ($version > 4) {
        $plugins['eclbutton'] = array(
          'path' => drupal_get_path('module', 'know4pol_ecl') . '/plugins/eclbutton',
          'filename' => 'plugin.js',
          'load' => TRUE,
          'buttons' => array(
            'eclbutton' => t('ECL Button'),
          ),
        );
      }
      break;
  }
  return $plugins;
}

/**
 * Implements hook_wysiwyg_editor_settings_alter().
 */
function know4pol_ecl_wysiwyg_editor_settings_alter(&$settings, $context) {
  global $base_url;

  if ($context['profile']->editor == 'ckeditor') {
    // Apply source formating when viewing html source.
    $settings['apply_source_formatting'] = 1;
    $settings['cleanup_on_startup'] = TRUE;

    // Available default values: "p;h2;h3;h4;h5;h6".
    $settings['format_tags'] = "Paragraph;h2;h3;h4;h5;h6";

    // Change the default format p.
    $settings['format_Paragraph']['name'] = 'Paragraph';
    $settings['format_Paragraph']['element'] = 'p';

    // Settings ckeditor to use theme css.
    $settings['contentsCss'] = [
      '0' => $base_url . '/' . drupal_get_path('theme', 'ec_europa') . '/assets/styles/wysiwyg/editor.css',
      '1' => $base_url . '/' . drupal_get_path('theme', 'ec_europa') . '/assets/styles/europa.css',
    ];

    $settings['bodyClass'] = 'padding-wysiwyg-body';

    $full_html = ['full_html', 'full_html_track'];

    // Make sure the toolbar is there.
    if (!empty($settings['toolbar']) && in_array($context['profile']->format, $full_html)) {
      $new_toolbar = [];
      // These are our desired groupings.
      $new_toolbar[] = ['Format'];
      $new_toolbar[] = [
        'Bold',
        'Italic',
        'Underline',
        'Subscript',
        'Superscript',
        'SpecialChar',
        'HorizontalRule',
      ];
      $new_toolbar[] = ['BulletedList', 'NumberedList', 'Outdent', 'Indent'];
      $new_toolbar[] = ['PasteFromWord', 'PasteText', 'RemoveFormat'];
      $new_toolbar[] = ['Link', 'NextEuropaToken', 'Unlink', 'Anchor'];
      $new_toolbar[] = [
        'Table',
        'Blockquote',
        'media',
        'Iframe',
        'collapse',
        'eclbutton',
      ];

      $new_toolbar[] = ['Undo', 'Maximize'];
      $new_toolbar[] = [
        'lite_AcceptAll',
        'lite_RejectAll',
        'lite_AcceptOne',
        'lite_RejectOne',
        'lite_ToggleShow',
        'lite_ToggleTracking',
      ];
      $new_toolbar[] = ['ShowBlocks', 'Source'];
      $settings['toolbar'] = $new_toolbar;
    }

    elseif (!empty($settings['toolbar']) && $context['profile']->format == 'filtered') {
      $new_toolbar[] = [
        'dt_headings',
        'Link',
        'NextEuropaToken',
        'BulletedList',
      ];

      $new_toolbar[] = [
        'Undo',
        'Source',
      ];

      $settings['toolbar'] = $new_toolbar;
    }
  }
}
