<?php

/**
 * @file
 * Scheduler publishes and unpublishes nodes on dates specified by the user.
 */

// The default time that will be used, until Admin sets a different value.
define('BULK_SCHEDULE_DATE_FORMAT', 'Y-m-d H:i:s');
define('BULK_SCHEDULE_PUBLICATION_DATETIME', '2019-03-30 00:00:00');

/**
 * Implements hook_permission().
 */
function bulk_schedule_permission() {
  return array(
    'administer bulk schedule' => array(
      'title' => t('Administer bulk schedule'),
      'description' => t('Configure bulk schedule options'),
    ),
    'schedule content for publication' => array(
      'title' => t('Update content for bulk scheduling'),
      'description' => t('Allows users to set revision for automatic publication with bulk scheduling'),
    ),

  );
}

/**
 * Implements hook_menu().
 */
function bulk_schedule_menu() {
  $items = array();
  $items['admin/config/content/bulk_schedule'] = array(
    'title' => 'Bulk schedule',
    'description' => "Configure settings and killswitch",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bulk_schedule_admin'),
    'access arguments' => array('administer bulk schedule'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'bulk_schedule.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_form_alter().
 */
function bulk_schedule_form_alter(&$form, $form_state) {
  // On edit node form.
  if (!empty($form['#node_edit_form'])) {
    $node = $form['#node'];

    // Get status and display message.
    if ($bulk_schedule = (isset($node->bulk_schedule) && $node->bulk_schedule)) {
      $locked = t('This content is locked since there is a revision scheduled for publication.');
      drupal_set_message($locked, 'status');
    }

    // Allowed to manage the scheduling.
    if (user_access('schedule content for publication')) {
      $form['options']['bulk_schedule'] = array(
        '#type' => 'checkbox',
        '#title' => t('Part of bulk scheduled publishing (Leave this revision in draft)'),
        '#default_value' => $bulk_schedule ? 1 : 0,
        '#weight' => 3,
      );
    }
    // If not allwowed and revision is sheduled, lock the content.
    elseif ($bulk_schedule) {
      // Lock all fields and buttons.
      foreach ([$form, $form['actions']] as $item) {
        foreach ($item as $key => $value) {
          if (drupal_substr($key, 0, 1) != '#' && is_array($form[$key])) {
            $form[$key]['#disabled'] = TRUE;
            $form[$key]['#attributes']['title'] = $locked;
          }
        }
      }
    }
  }
}

/**
 * Implements hook_node_load().
 */
function bulk_schedule_node_load($nodes, $types) {
  $nids = array_keys($nodes);
  $result = db_query('SELECT * FROM {bulk_schedule} WHERE nid IN (:nids)', array(':nids' => $nids));
  foreach ($result as $record) {
    $nid = $record->nid;
    $nodes[$nid]->bulk_schedule = 1;
  }
}

/**
 * Implements hook_node_view().
 */
function bulk_schedule_node_view($node, $view_mode, $langcode) {
  if (in_array($view_mode, array('full', 'featured')) && isset($node->bulk_schedule) && $node->bulk_schedule && node_is_page($node) && user_access('schedule content for publication')) {
    drupal_set_message(t('This content has revision scheduled for publication'), 'status');
  }
}

/**
 * Implements hook_node_presave().
 */
function bulk_schedule_node_presave($node) {
  // Set for schedule.
  if (isset($node->bulk_schedule) && $node->bulk_schedule) {
    drupal_set_message(t('Content will be published with Bulk schedule'), 'status');
  }
}

/**
 * Implements hook_node_insert().
 */
function bulk_schedule_node_insert($node) {
  if (isset($node->bulk_schedule) && $node->bulk_schedule) {
    db_insert('bulk_schedule')->fields(array(
      'nid' => $node->nid,
      'vid' => $node->vid,
    ))->execute();
  }
}

/**
 * Implements hook_node_update().
 */
function bulk_schedule_node_update($node) {
  // Update DB with checkbox value.
  if (isset($node->bulk_schedule) && $node->bulk_schedule) {
    // If not draft, consider this is not checked.
    if ($node->workbench_moderation_state_new != 'published') {
      db_merge('bulk_schedule')->key(array('nid' => $node->nid))->fields(array(
        'vid' => $node->vid,
      ))->execute();
    }
  }
  else {
    bulk_schedule_node_delete($node);
  }
}

/**
 * Implements hook_node_delete().
 */
function bulk_schedule_node_delete($node) {
  db_delete('bulk_schedule')->condition('nid', $node->nid)->execute();
}

/**
 * Implements hook_cron().
 */
function bulk_schedule_cron() {
  // Check if Bulk Scheduler is active.
  $active = variable_get('bulk_schedule_active', FALSE);
  $when = variable_get('bulk_schedule_publication_datetime', NULL);

  if (!$active || $when == NULL) {
    return;
  }

  $when = strtotime($when);
  $now = time();

  if ($when > $now) {
    return;
  }

  watchdog('bulk_schedule', 'Cron Bulk Schedule starts', NULL, WATCHDOG_NOTICE);
  // Load the cron functions file.
  module_load_include('inc', 'bulk_schedule', 'bulk_schedule.cron');

  // Use drupal_static to find out if bulk_schedule cron is running.
  // @see bulk_schedule_is_running()
  $bulk_schedule = &drupal_static(__FUNCTION__, FALSE);
  $bulk_schedule = TRUE;

  // Clear cache if node got published
  // Varnish has already purge rules but list and search pages need to.
  if (_bulk_schedule_publish()) {
    cache_clear_all();
  }
  // If no results, we could deactivate but it's temp, no need.
  // Reset the static scheduler_cron flag.
  drupal_static_reset(__FUNCTION__);
}

/**
 * Return whether bulk_schedule cron is running.
 *
 * @return bool
 *   TRUE if bulk_schedule_cron is currently running. FALSE if not.
 */
function bulk_schedule_cron_is_running() {
  return drupal_static('bulk_schedule_cron');
}

/**
 * Publish nodes with Bulk Schedule.
 *
 * @return bool
 *   TRUE if any node has been published, FALSE otherwise.
 */
function _bulk_schedule_publish() {
  $result = FALSE;

  // Get all content set for publication.
  $query = db_select('bulk_schedule', 's');
  $query->addField('s', 'nid');
  $query->addField('s', 'vid');
  $query->addJoin('INNER', 'node', 'n', 's.nid = n.nid');
  $query_result = $query->execute();

  $nids = array();
  $vids = array();
  while ($node = $query_result->fetchObject()) {
    $nids[] = $node->nid;
    $vids[$node->nid] = $node->vid;
  }

  foreach ($nids as $nid) {
    // Load specific revision (issue with published node always recreated).
    $node_revision = node_load($nid, $vids[$nid]);

    watchdog('bulk_schedule', 'Publishing node @type: %title.', array('@type' => $node_revision->type, '%title' => $node_revision->title), WATCHDOG_NOTICE, l(t('view'), 'node/' . $node_revision->nid, array('alias' => TRUE)));

    $node_revision->workbench_moderation_state_new = workbench_moderation_state_published();
    $node_revision->revision = FALSE;
    // Unset bulk_schedule value, bulk_schedule_node_update() will remove it.
    $node_revision->bulk_schedule = 0;
    $node_revision->changed = time();
    $node_revision->log = 'bulk schedule automatic publishing';
    node_save($node_revision);

    $result = TRUE;
  }

  return $result;
}

/**
 * Implements hook_views_api().
 */
function bulk_schedule_views_api() {
  return array(
    'api' => 3,
  );
}
